Feature: Login
lucasreno/origins-riott pull request #1
Opened 2021-11-27 15:50 UTC by lucasreno

2021-11-27 15:56 UTC, lucasreno commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RIOTT] 01 - Login dos responsáveis](https://trello.com/c/f4YxzSvR/296-riott-01-login-dos-respons%C3%A1veis)

2021-11-27 20:19 UTC, matheus-yudi-helpper requested changes
Faltou criar um `middleware` que vai ser aplicado em todas as rotas privadas da api.

A ideia é ter um uma classe que irá verificar pela presença do `token` na requisição. Ou seja, em todas as rotas privadas, que necessitam de autenticação, esse middleware será chamado e vai executar a validação do token.

2021-11-27 20:19 UTC, matheus-yudi-helpper commented on src/modules/auth/v1/controllers/AuthController.ts
> +    public async add(req: Request, res: Response): Promise<void> {
O nome do método pode ser login.

2021-12-03 21:28 UTC, matheus-yudi-helpper requested changes

2021-12-03 21:28 UTC, matheus-yudi-helpper commented on src/config/swagger.ts
> +        host: '34.136.200.153:4444',
Adicionar opção para rodar local também, da uma olhada aqui na doc do swagger: https://swagger.io/docs/specification/api-host-and-base-path/

2021-12-03 21:28 UTC, matheus-yudi-helpper commented on src/modules/auth/v1/controllers/AuthController.ts
> +        const checkPassword = await bcryptjs.compare(password, emailUser?.password || '');
Aqui não precisaria do `?` pois só vai chegar aqui se o **emailUser** existir, já que o if barra caso contrário.

2021-12-03 21:28 UTC, matheus-yudi-helpper commented on src/modules/auth/v1/controllers/AuthController.ts
> +    public async testToken(req: Request, res: Response): Promise<void> {
Pode remover este método.

2021-12-03 21:28 UTC, matheus-yudi-helpper commented on src/modules/auth/v1/middlewares/AuthValidator.ts
> +            isString: true,
Precisa validar se é string também?

2021-12-03 21:28 UTC, matheus-yudi-helpper commented on src/modules/users/v1/controllers/UserController.ts
> -    @PublicRoute()
Vai manter esse endpoint como privado? Se sim, pode deixar os demais aqui do **UserController** como privado também.

2021-12-06 11:24 UTC, matheus-yudi-helpper approved these changes

2021-12-06 22:19 UTC, merged