Feature: Member
lucasreno/origins-riott pull request #3
Opened 2021-12-10 02:17 UTC by lucasreno

2021-12-15 02:46 UTC, lucasreno commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RIOTT] 03 - Cadastro de membros](https://trello.com/c/DaYSY3t9/334-riott-03-cadastro-de-membros)

2021-12-16 23:56 UTC, matheus-yudi-helpper requested changes

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +        const memberRepository: MemberRepository = new MemberRepository();
Pode usar o repository diretamente, sem atribuir numa variável.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +        };
Coloca uma linha entre as declarações e o if.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +     *         name: taskId
Corrigir o name.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/DateUtils.ts
> + * ObjectUtils
Corrigir o nome.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +            if (statusUpload && statusUpload.status === EnumStatus.SUCCESS) {
Aqui pode usar o `?` no lugar de verificar com o `&&`.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/models/EnumStatus.ts
> +export enum EnumStatus {
Daria para usar `boolean` ou o próprio atributo.

Nos enums tem como fazer assim:

```ts
// Usar um nome mais específico para o enum
export enum EnumFileUploadStatus {
    SUCCESS,
    ERROR,
}
```

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/models/IStatusUpload.ts
> +export interface IStatusUpload {
Creio que ficaria mais fácil na hora de manipular se fosse `IUploadResponse`, contendo o `status` e um `data` ou `content`. O que acha?

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +            if (statusUpload && statusUpload.status === EnumStatus.SUCCESS) {
Aqui pode usar o `?` no lugar de verificar com o `&&`.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +            const fileUtils: FileUtils = new FileUtils();
Coloca alguns espaços entre as declarações e a lógica do código.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/FileUtils.ts
> +        // console.log(statusUpload.message);
Remover o console.log

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/FileUtils.ts
> +            const createOrFail = 'wx';
Pode usar o valor direto.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/models/EnumConstants.ts
> +    URL_FILES = 'http://34.136.200.153/'
Não ficaria mais intuitivo nomear como `STORAGE_URL` ?

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/FileUtils.ts
> +            statusUpload.message = `Não foi possível gravar o arquivo: ${error}`;
Talvez não seja interessante mandar esse erro para o front, apenas a mensagem já é o suficiente.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/FileUtils.ts
> +     *
Faltou o @params

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/FileUtils.ts
> +    public uploadFile(req: Request): IStatusUpload {
A função poderia receber direto o `file`, já que não está utilizando mais nada do objeto `req`.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +        const member: Member = memberRef;
Aqui daria para fazer:

```ts
const member: Member = {
   ...memberRef,
   name,
   birthday,
   reward,
}
```

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +                RouteResponse.error(statusUpload.message, res);
Não precisou do return aqui? Ele para a execução?

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +        RouteResponse.success({ rows, count, url }, res);
Pode usar o Enum direto no objeto.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +        RouteResponse.success({ ...req.body.memberRef, url }, res);
pode usar o Enum direto no objeto.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/config/multer.ts
> +    const extension = file.mimetype.split('/').pop();
Pode deixar a criação da `const` dentro do if, assim se não passar na validação evita a criação dela.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +        const member: Member = memberRef;
Aqui daria para fazer:

```ts
const member: Member = {
   ...memberRef,
   deletedAt: new Date()
}
```

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/DateUtils.ts
> +     * dateLimitToEighteen
Corrigir o nome.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/DateUtils.ts
> +    public static getDateLimitToEighteen(): string {
Não é um método muito específico para ficar no `utils`? Talvez só colocar no `validator` como uma função separada já fica legal.

2021-12-16 23:56 UTC, matheus-yudi-helpper commented on src/utils/FileUtils.ts
> +        const fullpath = `${path}${photo}`;
Pode usar o enum direto.

2021-12-17 03:49 UTC, lucasreno commented on src/utils/FileUtils.ts
> +            const createOrFail = 'wx';
O parâmetro flag da função writeFileSync aceita apenas um string ou undefined.

2021-12-17 03:57 UTC, lucasreno commented on src/modules/member/v1/controllers/MemberController.ts
> +                RouteResponse.error(statusUpload.message, res);
Não simular um erro para testar, vou testar isso amanhã.

2021-12-17 03:59 UTC, lucasreno commented on src/modules/member/v1/controllers/MemberController.ts
> +        RouteResponse.success({ rows, count, url }, res);
Não deu certo colocar direito .-.

2021-12-17 03:59 UTC, lucasreno commented on src/modules/member/v1/controllers/MemberController.ts
> +        RouteResponse.success({ ...req.body.memberRef, url }, res);
Não deu certo colocar direito .-.

2021-12-18 12:54 UTC, lucasreno commented on src/modules/member/v1/controllers/MemberController.ts
> +                RouteResponse.error(statusUpload.message, res);
Realmente, ele retornava apenas o 400 como resposta mas o código seguia.

2021-12-21 00:12 UTC, matheus-yudi-helpper requested changes
Toop, ficou só mais alguns detalhezinhos.

2021-12-21 00:12 UTC, matheus-yudi-helpper commented on src/models/IStatusUpload.ts
> +import { EnumFileUploadStatus } from './EnumStatus';
Faltou alterar o nome do arquivo.

2021-12-21 00:12 UTC, matheus-yudi-helpper commented on src/App.ts
> +        // this.app.use(fileMiddleware); // Trata arquivos enviados para rota e adiciona no express.req
Faltou apagar essa linha.

2021-12-21 00:12 UTC, matheus-yudi-helpper commented on src/models/EnumStatus.ts
> +export enum EnumFileUploadStatus {
Faltou alterar o nome do arquivo.

2021-12-21 00:12 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +        RouteResponse.success({ rows, count, url }, res);
Assim `url: EnumEndpoints.URL` ?

2021-12-21 00:12 UTC, matheus-yudi-helpper commented on src/modules/member/v1/controllers/MemberController.ts
> +        RouteResponse.success({ ...req.body.memberRef, url }, res);
Assim `url: EnumEndpoints.URL` ?

2021-12-21 00:12 UTC, matheus-yudi-helpper commented on src/modules/member/v1/middlewares/MemberValidator.ts
> +     * @returns Objeto tratado
Corrigir o @returns.

2021-12-21 00:12 UTC, matheus-yudi-helpper commented on src/utils/FileUtils.ts
> +            const createOrFail = 'wx';
Não tem como usar `flag: 'wx'` então?

2021-12-21 00:12 UTC, matheus-yudi-helpper commented on src/utils/FileUtils.ts
> +        const fullpath = `${EnumConstants.PATH_UPLOAD}${photo}`;
Pode passar direto.

2021-12-21 21:24 UTC, lucasreno commented on src/utils/FileUtils.ts
> +            const createOrFail = 'wx';
Tem razão Yudi, tava viajando, rsrs.
Agora esse caso especifico eu acho melhor manter dessa maneira pro código ficar mais legível.
O que acha?

2021-12-21 21:26 UTC, lucasreno commented on src/modules/member/v1/controllers/MemberController.ts
> +        RouteResponse.success({ rows, count, url }, res);
Deu certo sim, eu que viajei, rsrs.

2021-12-21 21:26 UTC, lucasreno commented on src/modules/member/v1/controllers/MemberController.ts
> +        RouteResponse.success({ rows, count, url }, res);
Já corrigi em todos os locais que estava dessa maneira

2021-12-21 23:08 UTC, matheus-yudi-helpper approved these changes

2021-12-21 23:08 UTC, merged