Features: Tasklist
lucasreno/origins-riott pull request #4
Opened 2021-12-17 03:29 UTC by lucasreno

2021-12-20 00:25 UTC, lucasreno commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RIOTT] 02 - Listas de marcação + 05 - Relacionamento de atividades + 06 - Historico de mesadas](https://trello.com/c/dKMLgCQV/336-riott-02-listas-de-marca%C3%A7%C3%A3o-05-relacionamento-de-atividades-06-historico-de-mesadas)

2021-12-20 00:25 UTC, lucasreno commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RIOTT] 02 - Listas de marcação + 05 - Relacionamento de atividades + 06 - Historico de mesadas](https://trello.com/c/dKMLgCQV/336-riott-02-listas-de-marca%C3%A7%C3%A3o-05-relacionamento-de-atividades-06-historico-de-mesadas)

2021-12-21 00:55 UTC, matheus-yudi-helpper requested changes
Muito bom Lucas, ta voando.

Veja se algumas das lógicas dos `validadores/controller` podem ser abstráidas por uma query dentro do Repository, daria uma boa limpada no código deles e fica mais separado as responsabilidades.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/library/database/entity/TaskList.ts
> +    public taskListItem: { taskId: string; discount: number; failed: boolean; task: Task }[];
Não tem como criar e tipar com uma entity TaskListItem ? `Array<TaskListItem>`

É legal alterar o nome para o plural também.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/library/database/repository/TaskListRepository.ts
> +        return this.getConnection().getMongoRepository(TaskList).findAndCount(options);
Da para colocar o if dentro do acesso a propriedade:

```ts
return this.getConnection().getMongoRepository(TaskList)[onlyCount ? 'count' : 'findAndCount'](options);
```

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/library/database/repository/TaskListRepository.ts
> +     * findByMemberId
Corrigir os comentários, titulo e params

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +        /* Esse ta funcionando
Que houve aqui ? kkkk

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +     *             enum: ['Em andamento', 'Em espera', 'Finalizada']
Pode colocar os valores que precisam ser enviados do enum, tipo "PENDING"...

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +    public async getStatus(req: Request, res: Response): Promise<void> {
getStatus da a entender que ta buscando o status, pode usar o nome da própria rota que ta legal.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +        const tasks: Task[] | undefined = await new TaskRepository().find<Task>();
Não seria melhor deixar essa busca dentro do `appendMembersAndTasks` ? Já que ta precisando buscar toda vez que usar esse método.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +            member.tasklist = rows.filter(tasklist => tasklist.memberId === `${member.id}`);
Não daria para usar um método do repository e filtrar pelas queries do mongo?

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +    @PublicRoute()
Vai ser uma rota pública?

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +        const { taskListRef } = req.body;
Se não precisar utilizar mais de uma vez, pode usar o valor direto em vez de guardar na variável.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +        const { taskListRef } = req.body;
Se não precisar utilizar mais de uma vez, pode usar o valor direto em vez de guardar na variável.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +        const taskListRepository: TaskListRepository = new TaskListRepository();
Pode usar direto.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +            data.failed = false;
Quando editar vai sempre resetar para false mesmo?

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +    private static appendMembersAndTasks(rows: TaskList[], members: Member[], tasks: Task[]): TaskList[] {
Faltou o comentário :cry:

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +            const getStatitics = row.status === EnumStatusTaskList.RUNNING || row.status === EnumStatusTaskList.CLOSED;
Corrigir o nome da variável.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        const { memberId } = req.body;
Da para puxar essa abstração para fora do if e acrescentar nela o `id` também

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                                if (taskList && taskList.memberId === memberId) check = true;
Da para atribuir o if no check, em vez de setar o check na mão.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        const { taskListItem } = req.body;
Puxar para fora do if e acrescentar espaços entre os ifs e a lógica.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        const { memberId } = req.params;
Puxar para fora do if.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        if (member) check = true;
Da para fazer `check = !!member`

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                            if (tasks[i].taskId === req.params?.taskId) check = true;
Da para atribuir o if direto no check.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        const tasks = req.body.taskListRef.taskListItem;
Abstrair com desconstrução do `req.body.taskListRef`

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                    if (req.body.taskListRef.status !== EnumStatusTaskList.CLOSED) check = true;
Nem precisa do if, pode fazer direto no return.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                    if (req.body.taskListRef.status === EnumStatusTaskList.RUNNING) check = true;
Nem precisa do if, pode fazer direto no return.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                    if (req.body.taskListRef.status === EnumStatusTaskList.PENDING) check = true;
Nem precisa do if, pode fazer direto no return.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                options: async (_: string, { req }) => {
Daria para abstrair esse options numa função e informar `minhaFuncao(status)` na hora de usar.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        for (let i = 0; i < totalTasks; i += 1) {
Da para trocar por um `.some` ou `.every` para validar os descontos.

2021-12-21 00:55 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        if (validIds.length === totalTasks && verifiedIds.length === totalTasks) check = true;
Da para atribuir direto no if ?

2021-12-22 00:33 UTC, lucasreno commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +        /* Esse ta funcionando
Kkkkkkkkkk, tomei uma surra pra promises, aí deixei só o trecho que eu consegui fazer funcionar antes de refatorar o código. Já removi :P

2021-12-22 00:36 UTC, lucasreno commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +     *             enum: ['Em andamento', 'Em espera', 'Finalizada']
Amanhã eu converso com você sobre esse

2021-12-22 00:40 UTC, lucasreno commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +            member.tasklist = rows.filter(tasklist => tasklist.memberId === `${member.id}`);
Daria sim, vamos conversa amanhã sobre esse ponto também

2021-12-22 00:42 UTC, lucasreno commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +    @PublicRoute()
Ops, :-1:

2021-12-22 00:49 UTC, lucasreno commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +            data.failed = false;
Primeiramente não haveria necessidade, pois só é possível alterar listas 'Em espera'. 
Porém, se eu não setar este atributo ele sobrescreve o subdocumento "taskListItems" sem esse atributo :cry:

2021-12-22 00:49 UTC, lucasreno commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +    private static appendMembersAndTasks(rows: TaskList[], members: Member[], tasks: Task[]): TaskList[] {
Emocionei, já vou documentar, :rofl:

2021-12-22 01:06 UTC, lucasreno commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        const { memberId } = req.params;
Conversar com você sobre esse ponto também

2021-12-22 01:17 UTC, lucasreno commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                options: async (_: string, { req }) => {
Conversar sobre esse

2021-12-22 01:26 UTC, lucasreno commented on src/modules/tasklist/v1/middlewares/TaskListValidator.ts
> +                        if (validIds.length === totalTasks && verifiedIds.length === totalTasks) check = true;
Dá sim :+1:

2021-12-22 02:19 UTC, matheus-yudi-helpper commented on src/modules/tasklist/v1/controllers/TaskListController.ts
> +     *             enum: ['Em andamento', 'Em espera', 'Finalizada']
Esse ta certo, pode desconsiderar. Perdão pelo vacilo kk.

2022-01-28 14:26 UTC, merged